//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.13 at 10:50:16 PM BST 
//


package com.ezar.clickandeat.data;

import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (com.ezar.clickandeat.data.converter.DateConverter.parseDate(value));
    }

    public String marshal(Date value) {
        return (com.ezar.clickandeat.data.converter.DateConverter.printDate(value));
    }

}
